apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pratyushs93/sample-project.git
    targetRevision: main
    path: templates
  destination:
    server: https://kubernetes.default.svc
    namespace: default

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: guestbook
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/argoproj/argocd-example-apps.git
#     targetRevision: HEAD
#     path: guestbook
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: guestbook